import type { DashboardStats, GenerationTask, User, Workflow } from "./types";

export const mockStats: DashboardStats = {
  total_users: 1284,
  active_users: 1098,
  queued_tasks: 18,
  running_tasks: 7,
  completed_tasks: 42130,
  credits_spent: 982410,
};

export const mockUsers: User[] = [
  {
    id: 1,
    telegram_id: "711820445",
    username: "studio_mira",
    display_name: "Mira Chen",
    status: "active",
    membership_tier: "studio",
    credit_balance: 1840,
    total_spent_credits: 20390,
    created_at: "2026-04-21T08:30:00Z",
    updated_at: "2026-04-28T05:20:00Z",
  },
  {
    id: 2,
    telegram_id: "503188902",
    username: "framecraft",
    display_name: "Frame Craft",
    status: "active",
    membership_tier: "pro",
    credit_balance: 612,
    total_spent_credits: 9340,
    created_at: "2026-04-22T11:44:00Z",
    updated_at: "2026-04-28T06:18:00Z",
  },
  {
    id: 3,
    telegram_id: "913588201",
    username: "nora_ai",
    display_name: "Nora",
    status: "limited",
    membership_tier: "starter",
    credit_balance: 76,
    total_spent_credits: 1288,
    created_at: "2026-04-25T13:12:00Z",
    updated_at: "2026-04-28T03:02:00Z",
  },
  {
    id: 4,
    telegram_id: "810944018",
    username: "visual_lab",
    display_name: "Visual Lab",
    status: "active",
    membership_tier: "free",
    credit_balance: 22,
    total_spent_credits: 180,
    created_at: "2026-04-27T10:50:00Z",
    updated_at: "2026-04-27T16:33:00Z",
  },
];

export const mockTasks: GenerationTask[] = [
  {
    id: 9001,
    user_id: 1,
    workflow_id: 1,
    kind: "image.generate",
    status: "running",
    original_text: "赛博茶室，夜景，柔和灯光",
    interpreted_prompt: "A cinematic cyberpunk tea room at night with soft practical lighting.",
    source_media_url: null,
    result_urls: [],
    credit_cost: 6,
    error_message: null,
    external_job_id: "a1f3-queue-88",
    created_at: "2026-04-28T07:40:00Z",
    updated_at: "2026-04-28T07:41:00Z",
  },
  {
    id: 9000,
    user_id: 2,
    workflow_id: 3,
    kind: "video.image_to_video",
    status: "queued",
    original_text: "让这张产品图镜头慢慢推进",
    interpreted_prompt: "Slow camera push-in with subtle product light movement.",
    source_media_url: "https://example.com/source.png",
    result_urls: [],
    credit_cost: 18,
    error_message: null,
    external_job_id: null,
    created_at: "2026-04-28T07:37:00Z",
    updated_at: "2026-04-28T07:37:00Z",
  },
  {
    id: 8997,
    user_id: 3,
    workflow_id: 2,
    kind: "image.edit",
    status: "failed",
    original_text: "把背景改成高级灰展厅",
    interpreted_prompt: "Replace the background with a refined neutral gallery showroom.",
    source_media_url: "https://example.com/edit.png",
    result_urls: [],
    credit_cost: 8,
    error_message: "ComfyUI timeout after 30s",
    external_job_id: "a1f3-queue-71",
    created_at: "2026-04-28T07:18:00Z",
    updated_at: "2026-04-28T07:19:00Z",
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: 1,
    name: "SDXL Prompt To Image",
    kind: "image.generate",
    comfy_workflow_key: "sdxl-text-to-image",
    credit_cost: 6,
    is_active: true,
    description: "Generate images from text prompts.",
    created_at: "2026-04-28T06:00:00Z",
  },
  {
    id: 2,
    name: "Image Edit Assistant",
    kind: "image.edit",
    comfy_workflow_key: "image-edit-inpaint",
    credit_cost: 8,
    is_active: true,
    description: "Edit or restyle uploaded images.",
    created_at: "2026-04-28T06:00:00Z",
  },
  {
    id: 3,
    name: "Image To Video Motion",
    kind: "video.image_to_video",
    comfy_workflow_key: "image-to-video",
    credit_cost: 18,
    is_active: true,
    description: "Animate user images into short videos.",
    created_at: "2026-04-28T06:00:00Z",
  },
  {
    id: 4,
    name: "Image Understanding Prompt Writer",
    kind: "prompt.expand",
    comfy_workflow_key: "prompt-expand",
    credit_cost: 2,
    is_active: true,
    description: "Understand media and expand user intent.",
    created_at: "2026-04-28T06:00:00Z",
  },
];
